#include <feature_detection/detectors.h>
#include <imgproc/imgproc.h>
#include <keypoint_t/keypoint_t.h>
#include <keypoints/keypoints.h>
#include <keypoints_filter/keypoints_filter.h>
#include <matrix_smart/matrix_smart.h>
#include <matrix_t/matrix_t.h>
#include <orb/orb.h>
#include <pyramid_t/pyramid_t.h>
#include <types/types.h>
#include <yape06/yape06.h>